import type { LangCode } from './i18n';

type Translation = Record<LangCode, string>;

export type GuideBlock =
  | { kind: 'h'; text: Translation }
  | { kind: 'sub'; text: Translation }
  | { kind: 'row'; label: Translation; value: Translation }
  | { kind: 'note'; text: Translation }
  | { kind: 'bullet'; text: Translation };

export const LANGUAGES: Array<{ code: LangCode; label: string }> = [
  { code: 'en', label: 'English' },
  { code: 'tr', label: 'Türkçe' },
  { code: 'de', label: 'Deutsch' },
  { code: 'fr', label: 'Français' },
  { code: 'ar', label: 'العربية' },
];

export const MENU_TEXT = {
  page_language: { tr: 'DİL SEÇENEKLERİ', en: 'LANGUAGE', de: 'SPRACHE', fr: 'LANGUE', ar: 'اللغة' },
  page_guide: { tr: 'KULLANIM KILAVUZU', en: 'USER GUIDE', de: 'BENUTZERHANDBUCH', fr: "GUIDE D'UTILISATION", ar: 'دليل المستخدم' },
  page_about: { tr: 'HAKKIMIZDA', en: 'ABOUT', de: 'ÜBER UNS', fr: 'À PROPOS', ar: 'حول' },
  page_mission: { tr: 'MİSYON & VİZYON', en: 'MISSION & VISION', de: 'MISSION & VISION', fr: 'MISSION & VISION', ar: 'المهمة والرؤية' },
  page_contact: { tr: 'İLETİŞİM', en: 'CONTACT', de: 'KONTAKT', fr: 'CONTACT', ar: 'تواصل' },
  menu_language: { tr: '🌐 Dil / Language', en: '🌐 Language', de: '🌐 Sprache', fr: '🌐 Langue', ar: '🌐 اللغة' },
  menu_guide: { tr: '📖 Kullanım Kılavuzu', en: '📖 User Guide', de: '📖 Anleitung', fr: '📖 Guide', ar: '📖 دليل' },
  menu_about: { tr: 'Hakkımızda', en: 'About', de: 'Über uns', fr: 'À propos', ar: 'حول' },
  menu_mission: { tr: 'Misyon & Vizyon', en: 'Mission & Vision', de: 'Mission', fr: 'Mission', ar: 'المهمة' },
  menu_contact: { tr: 'İletişim', en: 'Contact', de: 'Kontakt', fr: 'Contact', ar: 'تواصل' },
  back: { tr: '← GERİ', en: '← BACK', de: '← ZURÜCK', fr: '← RETOUR', ar: '← رجوع' },
} satisfies Record<string, Translation>;

export const PAGE_TEXT = {
  about: {
    tr: 'ANATOLİA-SİM, Bold Askeri Teknoloji ve Savunma Sanayi A.Ş. bünyesinde Yalçın Atabey tarafından geliştirilen, simülasyon hipotezini deneysel olarak test etmeye yönelik ileri düzey bir medeniyet simülasyon platformudur.\n\nGerçek biyolojik, genetik, çevresel ve sosyal mekanizmaları temel alarak iki bireyden başlayan bir nüfusun binlerce yıl boyunca nasıl evrildiğini, dil, inanç, teknoloji ve devlet yapılarını nasıl geliştirdiğini müdahalesiz biçimde gözlemlemeyi sağlar.\n\nProje Kodu: RST Q-Nation 200120401018',
    en: 'ANATOLIA-SIM is an advanced civilization simulation platform developed by Yalçın Atabey under Bold Askeri Teknoloji ve Savunma Sanayi A.Ş., designed to experimentally test the simulation hypothesis.\n\nIt models biological, genetic, environmental and social mechanisms, observing a population that starts from two individuals and evolves over thousands of years toward language, belief, technology and governance.\n\nProject Code: RST Q-Nation 200120401018',
    de: 'ANATOLIA-SIM ist eine fortschrittliche Zivilisationssimulationsplattform, entwickelt von Yalçın Atabey unter Bold Askeri Teknoloji ve Savunma Sanayi A.Ş., um die Simulationshypothese experimentell zu testen.\n\nSie modelliert biologische, genetische, ökologische und soziale Mechanismen und beobachtet eine Bevölkerung, die mit zwei Individuen beginnt und sich über Jahrtausende zu Sprache, Glauben, Technologie und Regierung entwickelt.\n\nProjektcode: RST Q-Nation 200120401018',
    fr: "ANATOLIA-SIM est une plateforme avancée de simulation de civilisation développée par Yalçın Atabey au sein de Bold Askeri Teknoloji ve Savunma Sanayi A.Ş., conçue pour tester expérimentalement l'hypothèse de simulation.\n\nElle modélise des mécanismes biologiques, génétiques, environnementaux et sociaux, en observant une population issue de deux individus évoluer vers le langage, la croyance, la technologie et la gouvernance.\n\nCode du projet : RST Q-Nation 200120401018",
    ar: 'ANATOLIA-SIM منصة متقدمة لمحاكاة الحضارة طوّرها يالتشين أتابي ضمن Bold Askeri Teknoloji ve Savunma Sanayi A.Ş. لاختبار فرضية المحاكاة تجريبياً.\n\nتحاكي آليات بيولوجية وجينية وبيئية واجتماعية، وتراقب مجتمعاً يبدأ من فردين ويتطور عبر آلاف السنين نحو اللغة والمعتقد والتكنولوجيا والحوكمة.\n\nرمز المشروع: RST Q-Nation 200120401018',
  },
  mission: {
    tr: 'MİSYON\nSimülasyon hipotezini bilimsel ve deneysel zeminlerde test etmek; insan medeniyetinin evrensel örüntülerini ortaya çıkarmak.\n\nVİZYON\nDünyanın en kapsamlı yapay yaşam ve medeniyet simülasyon platformu olmak; insanlığın kökeni, bilinci ve geleceği hakkında nesnel veriler üretmek.',
    en: "MISSION\nTest the simulation hypothesis on scientific and experimental grounds and reveal universal patterns of human civilization.\n\nVISION\nBecome the world's most comprehensive artificial life and civilization simulation platform, producing objective data about the origin, consciousness and future of humanity.",
    de: 'MISSION\nDie Simulationshypothese auf wissenschaftlicher und experimenteller Grundlage testen und universelle Muster menschlicher Zivilisation sichtbar machen.\n\nVISION\nDie umfassendste Plattform für künstliches Leben und Zivilisationssimulation werden und objektive Daten über Ursprung, Bewusstsein und Zukunft der Menschheit erzeugen.',
    fr: "MISSION\nTester l'hypothèse de simulation sur des bases scientifiques et expérimentales et révéler les schémas universels de la civilisation humaine.\n\nVISION\nDevenir la plateforme la plus complète de simulation de vie artificielle et de civilisation, produisant des données objectives sur l'origine, la conscience et l'avenir de l'humanité.",
    ar: 'المهمة\nاختبار فرضية المحاكاة على أسس علمية وتجريبية وكشف الأنماط الكونية للحضارة الإنسانية.\n\nالرؤية\nأن تصبح المنصة الأشمل لمحاكاة الحياة الاصطناعية والحضارة، وإنتاج بيانات موضوعية حول أصل الإنسانية ووعيها ومستقبلها.',
  },
  contact: {
    tr: 'Proje Sahibi: Yalçın Atabey\nKuruluş: Bold Askeri Teknoloji ve Savunma Sanayi A.Ş.\nE-posta: info@boldkimya.com.tr\nTelefon: +90 532 217 07 76\nORCID: 0009-0004-9037-5750\n\n© 2026 Tüm hakları saklıdır.',
    en: 'Project Owner: Yalçın Atabey\nOrganization: Bold Askeri Teknoloji ve Savunma Sanayi A.Ş.\nE-mail: info@boldkimya.com.tr\nPhone: +90 532 217 07 76\nORCID: 0009-0004-9037-5750\n\n© 2026 All rights reserved.',
    de: 'Projektinhaber: Yalçın Atabey\nOrganisation: Bold Askeri Teknoloji ve Savunma Sanayi A.Ş.\nE-Mail: info@boldkimya.com.tr\nTelefon: +90 532 217 07 76\nORCID: 0009-0004-9037-5750\n\n© 2026 Alle Rechte vorbehalten.',
    fr: 'Propriétaire du projet : Yalçın Atabey\nOrganisation : Bold Askeri Teknoloji ve Savunma Sanayi A.Ş.\nE-mail : info@boldkimya.com.tr\nTéléphone : +90 532 217 07 76\nORCID : 0009-0004-9037-5750\n\n© 2026 Tous droits réservés.',
    ar: 'مالك المشروع: يالتشين أتابي\nالمنظمة: Bold Askeri Teknoloji ve Savunma Sanayi A.Ş.\nالبريد الإلكتروني: info@boldkimya.com.tr\nالهاتف: +90 532 217 07 76\nORCID: 0009-0004-9037-5750\n\n© 2026 جميع الحقوق محفوظة.',
  },
} satisfies Record<'about' | 'mission' | 'contact', Translation>;

export const GUIDE_BLOCKS: GuideBlock[] = [

  // ── 1. SİMÜLASYON OLUŞTURMA ──────────────────────────────────────────────
  { kind: 'h', text: { tr: '1 — SİMÜLASYON OLUŞTURMA', en: '1 — CREATING A SIMULATION', de: '1 — SIMULATION ERSTELLEN', fr: '1 — CRÉER UNE SIMULATION', ar: '١ — إنشاء المحاكاة' } },
  { kind: 'sub', text: { tr: 'Temel Bilgiler', en: 'Basic Info', de: 'Grundlagen', fr: 'Informations de base', ar: 'المعلومات الأساسية' } },
  { kind: 'row', label: { tr: 'Simülasyon Adı', en: 'Simulation Name', de: 'Simulationsname', fr: 'Nom de simulation', ar: 'اسم المحاكاة' }, value: { tr: 'Medeniyetinize anlamlı bir ad verin. Raporlarda, kontrol panelinde ve tüm ihracat dosyalarında görünür.', en: 'Give your civilization a meaningful name. It appears in reports, the dashboard and all export files.', de: 'Geben Sie Ihrer Zivilisation einen aussagekräftigen Namen. Er erscheint in Berichten, im Kontrollpanel und in allen Exportdateien.', fr: 'Donnez un nom significatif à votre civilisation. Il apparaît dans les rapports, le tableau de bord et tous les fichiers exportés.', ar: 'امنح حضارتك اسماً ذا معنى. يظهر في التقارير ولوحة التحكم وجميع ملفات التصدير.' } },
  { kind: 'row', label: { tr: 'Enlem / Boylam', en: 'Latitude / Longitude', de: 'Breite / Länge', fr: 'Latitude / Longitude', ar: 'خط العرض / خط الطول' }, value: { tr: 'Başlangıç koordinatları biyomu, iklimi, mevsim döngüsünü ve hastalık riskini doğrudan belirler. Tropik bölgeler sıtma riskini artırır; kutup bölgelerinde kaynak kıtlığı yaşanır.', en: 'Starting coordinates directly determine biome, climate, seasonal cycle and disease risk. Tropical regions increase malaria risk; polar regions face resource scarcity.', de: 'Die Startkoordinaten bestimmen direkt das Biom, das Klima, den Jahreszyklus und das Krankheitsrisiko. Tropische Regionen erhöhen das Malariarisiko; polare Regionen leiden unter Ressourcenknappheit.', fr: "Les coordonnées de départ déterminent directement le biome, le climat, le cycle saisonnier et le risque de maladie. Les régions tropicales augmentent le risque de paludisme ; les régions polaires souffrent de pénurie de ressources.", ar: 'تحدد إحداثيات البداية مباشرةً المنطقة الحيوية والمناخ ودورة المواسم وخطر المرض. تزيد المناطق الاستوائية من خطر الملاريا؛ وتعاني المناطق القطبية من شح الموارد.' } },

  { kind: 'sub', text: { tr: 'Kurucu Ayarları', en: 'Founder Settings', de: 'Gründer-Einstellungen', fr: 'Paramètres des fondateurs', ar: 'إعدادات المؤسسين' } },
  { kind: 'row', label: { tr: 'İsim & Yaş', en: 'Name & Age', de: 'Name & Alter', fr: 'Nom & Âge', ar: 'الاسم والعمر' }, value: { tr: 'Her kurucuya özel bir isim ve 16-60 arası başlangıç yaşı verilebilir. Yaş, üreme ömrünü ve ilk neslin genetik çeşitliliğini etkiler.', en: 'Each founder can have a custom name and a starting age of 16-60. Age affects reproductive lifespan and the genetic diversity of the first generation.', de: 'Jeder Gründer kann einen eigenen Namen und ein Startalter von 16-60 haben. Das Alter beeinflusst die Fortpflanzungslebensdauer und die genetische Vielfalt der ersten Generation.', fr: "Chaque fondateur peut avoir un nom personnalisé et un âge de départ de 16 à 60 ans. L'âge affecte la durée de vie reproductive et la diversité génétique de la première génération.", ar: 'يمكن منح كل مؤسس اسماً مخصصاً وعمر بداية يتراوح بين 16-60. يؤثر العمر في العمر الإنجابي والتنوع الجيني للجيل الأول.' } },
  { kind: 'row', label: { tr: 'Görünüş', en: 'Appearance', de: 'Aussehen', fr: 'Apparence', ar: 'المظهر' }, value: { tr: 'Göz rengi, saç rengi ve ten tonu seçilebilir. Bu özellikler kalıtım yoluyla sonraki nesillere geçer ve nüfus içinde fenotipik çeşitlilik oluşturur.', en: 'Eye colour, hair colour and skin tone can be selected. These traits are inherited by subsequent generations, creating phenotypic diversity within the population.', de: 'Augenfarbe, Haarfarbe und Hautton können gewählt werden. Diese Merkmale werden an nachfolgende Generationen vererbt und erzeugen phänotypische Vielfalt in der Population.', fr: "La couleur des yeux, des cheveux et le teint peuvent être sélectionnés. Ces traits sont hérités par les générations suivantes, créant une diversité phénotypique au sein de la population.", ar: 'يمكن اختيار لون العيون ولون الشعر ودرجة لون البشرة. تنتقل هذه السمات بالوراثة إلى الأجيال التالية مما يخلق تنوعاً ظاهرياً داخل المجتمع.' } },

  { kind: 'sub', text: { tr: 'Genetik Özellikler (20 Özellik)', en: 'Genetic Traits (20 Traits)', de: 'Genetische Merkmale (20 Merkmale)', fr: 'Traits génétiques (20 traits)', ar: 'السمات الجينية (20 سمة)' } },
  { kind: 'note', text: { tr: 'Her özellik 0-1 arasında bir değer alır ve kurucuların genomuna yazılır. Sıfırdan büyüme başlar; özellikler nesiller boyunca mutasyonla değişebilir.', en: "Each trait takes a value from 0-1 and is written into the founders' genomes. Growth begins from zero; traits can change through mutation across generations.", de: 'Jedes Merkmal nimmt einen Wert von 0-1 an und wird in das Genom der Gründer eingeschrieben. Das Wachstum beginnt bei null; Merkmale können durch Mutation über Generationen hinweg variieren.', fr: 'Chaque trait prend une valeur de 0 à 1 et est inscrit dans les génomes des fondateurs. La croissance commence à zéro ; les traits peuvent changer par mutation au fil des générations.', ar: 'تأخذ كل سمة قيمة من 0 إلى 1 وتُكتب في جينومات المؤسسين. يبدأ النمو من الصفر؛ ويمكن أن تتغير السمات عبر الطفرات عبر الأجيال.' } },
  { kind: 'bullet', text: { tr: 'ZİHİN — BİLİŞSEL: Zeka (teknoloji & keşif hızı), Merak (keşif & ticaret ağı), Dil Yeteneği (dil evrimi), Öğrenme Hızı (beceri kazanımı).', en: 'MIND — COGNITIVE: Intelligence (tech & discovery speed), Curiosity (exploration & trade), Language Capacity (language evolution), Learning Rate (skill acquisition).', de: 'GEIST — KOGNITIV: Intelligenz (Technologie & Entdeckungsrate), Neugier (Erkundung & Handel), Sprachfähigkeit (Sprachentwicklung), Lernrate (Kompetenzerwerb).', fr: "ESPRIT — COGNITIF : Intelligence (vitesse tech & découverte), Curiosité (exploration & commerce), Capacité langagière (évolution du langage), Taux d'apprentissage (acquisition de compétences).", ar: 'العقل — المعرفي: الذكاء (سرعة التقنية والاكتشاف)، الفضول (الاستكشاف والتجارة)، القدرة اللغوية (تطور اللغة)، معدل التعلم (اكتساب المهارات).' } },
  { kind: 'bullet', text: { tr: 'ZİHİN — KİŞİLİK: Disiplin (kaynak verimliliği), Öz Farkındalık (Theory of Mind gelişimi), Stres Direnci (psikolojik dayanıklılık), Risk Toleransı (avlanma & keşif cesurluğu), İnovasyon (teknoloji keşif şansı), Sanat Duygusu (sanat formu üretimi).', en: 'MIND — CHARACTER: Discipline (resource efficiency), Self Awareness (Theory of Mind), Stress Resilience (psychological toughness), Risk Tolerance (hunt & explore boldness), Innovation (tech discovery chance), Art Sense (art form creation).', de: 'GEIST — CHARAKTER: Disziplin (Ressourceneffizienz), Selbstwahrnehmung (Theory of Mind), Stressresilienz (psychologische Belastbarkeit), Risikobereitschaft (Jagd & Erkundungskühnheit), Innovation (Technologieentdeckungschance), Kunstsinn (Kunstformschöpfung).', fr: "ESPRIT — CARACTÈRE : Discipline (efficacité des ressources), Conscience de soi (Théorie de l'esprit), Résilience au stress (robustesse psychologique), Tolérance au risque (audace chasse & exploration), Innovation (chance de découverte tech), Sens artistique (création de formes d'art).", ar: 'العقل — الشخصية: الانضباط (كفاءة الموارد)، الوعي الذاتي (نظرية العقل)، المرونة من الإجهاد (المتانة النفسية)، تحمل المخاطر (جرأة الصيد والاستكشاف)، الابتكار (فرصة اكتشاف التقنية)، الحس الفني (إنشاء أشكال الفن).' } },
  { kind: 'bullet', text: { tr: 'SOSYAL: Empati (grup uyumu & ittifak), Sosyal Bağ (grup kurma eğilimi), Saldırganlık (çatışma olasılığı), İşbirliği (ticaret frekansı), Liderlik Eğilimi (hiyerarşi gelişimi).', en: 'SOCIAL: Empathy (group cohesion & alliances), Social Bonding (group formation), Aggression (conflict probability), Cooperation (trade frequency), Leadership (hierarchy development).', de: 'SOZIAL: Empathie (Gruppenzusammenhalt & Allianzen), Soziale Bindung (Gruppenbildung), Aggression (Konfliktwahrscheinlichkeit), Kooperation (Handelshäufigkeit), Führung (Hierarchieentwicklung).', fr: "SOCIAL : Empathie (cohésion & alliances), Lien social (formation de groupes), Agressivité (probabilité de conflit), Coopération (fréquence des échanges), Leadership (développement de hiérarchie).", ar: 'الاجتماعي: التعاطف (تماسك المجموعة والتحالفات)، الترابط الاجتماعي (تكوين المجموعات)، العدوانية (احتمالية الصراع)، التعاون (تكرار التجارة)، القيادة (تطور التسلسل الهرمي).' } },
  { kind: 'bullet', text: { tr: 'BEDEN: Fiziksel Güç (avlanma başarısı & liderlik rekabeti), Dayanıklılık (ölüm riski & uzun seferler), Bağışıklık (hastalık direnci), Üreme Dürtüsü (doğurganlık & nüfus büyümesi), Uzun Ömür (ortalama yaşam süresi).', en: 'BODY: Physical Strength (hunt success & leadership competition), Endurance (mortality risk & long journeys), Immunity (disease resistance), Fertility (birth rate & population growth), Longevity (average lifespan).', de: 'KÖRPER: Körperkraft (Jagderfolg & Führungskonkurrenz), Ausdauer (Sterblichkeitsrisiko & lange Reisen), Immunität (Krankheitsresistenz), Fruchtbarkeit (Geburtenrate & Bevölkerungswachstum), Langlebigkeit (durchschnittliche Lebenserwartung).', fr: "CORPS : Force physique (succès à la chasse & compétition pour le leadership), Endurance (risque de mortalité & longs voyages), Immunité (résistance aux maladies), Fertilité (taux de natalité & croissance démographique), Longévité (espérance de vie moyenne).", ar: 'الجسد: القوة الجسدية (نجاح الصيد ومنافسة القيادة)، التحمل (خطر الوفاة والرحلات الطويلة)، المناعة (مقاومة الأمراض)، الخصوبة (معدل الولادة ونمو السكان)، طول العمر (متوسط العمر المتوقع).' } },

  // ── 2. ANA EKRAN ──────────────────────────────────────────────────────────
  { kind: 'h', text: { tr: '2 — ANA EKRAN', en: '2 — MAIN SCREEN', de: '2 — HAUPTBILDSCHIRM', fr: '2 — ÉCRAN PRINCIPAL', ar: '٢ — الشاشة الرئيسية' } },
  { kind: 'sub', text: { tr: '3B Dünya Haritası', en: '3D World Map', de: '3D-Weltkarte', fr: 'Carte du monde 3D', ar: 'خريطة العالم ثلاثية الأبعاد' } },
  { kind: 'bullet', text: { tr: 'Her ışık noktası bir bireydir. Sarı = kurucu, mavi = erkek, pembe = kadın. Noktaya tıklayarak bireyin detay kartını açabilirsiniz.', en: "Each light point is an individual. Yellow = founder, blue = male, pink = female. Click a point to open the individual's detail card.", de: 'Jeder Lichtpunkt ist ein Individuum. Gelb = Gründer, Blau = männlich, Rosa = weiblich. Klicken Sie auf einen Punkt, um die Detailkarte der Person zu öffnen.', fr: "Chaque point lumineux est un individu. Jaune = fondateur, bleu = homme, rose = femme. Cliquez sur un point pour ouvrir la fiche de détail de l'individu.", ar: 'كل نقطة ضوئية تمثل فرداً. أصفر = المؤسس، أزرق = ذكر، وردي = أنثى. انقر على نقطة لفتح بطاقة تفاصيل الفرد.' } },
  { kind: 'bullet', text: { tr: 'Harita üzerinde biyom, sıcaklık, besin bolluğu ve su bolluğu göstergeleri canlı güncellenir. Kırmızı uyarılar kritik kaynak kıtlığını işaret eder.', en: 'Biome, temperature, food abundance and water abundance indicators update live on the map. Red alerts indicate critical resource scarcity.', de: 'Biom-, Temperatur-, Nahrungsmengen- und Wassermengenindikatoren werden auf der Karte live aktualisiert. Rote Warnungen signalisieren kritische Ressourcenknappheit.', fr: "Les indicateurs de biome, température, abondance de nourriture et d'eau se mettent à jour en direct sur la carte. Les alertes rouges signalent une pénurie critique de ressources.", ar: 'تتحدث مؤشرات المنطقة الحيوية ودرجة الحرارة ووفرة الغذاء والماء مباشرةً على الخريطة. تشير التحذيرات الحمراء إلى شح الموارد الحرج.' } },
  { kind: 'sub', text: { tr: 'Üst Bilgi Şeridi', en: 'Top Info Bar', de: 'Obere Informationsleiste', fr: "Barre d'info supérieure", ar: 'شريط المعلومات العلوي' } },
  { kind: 'bullet', text: { tr: 'Yıl, gün, nüfus, mutluluk, bilinç ortalaması ve dil evresi anlık olarak görüntülenir. WARP aktifken hedef yıl göstergesi sarı renkte belirir.', en: 'Year, day, population, happiness, average consciousness and language stage are displayed in real time. When WARP is active, the target year indicator appears in yellow.', de: 'Jahr, Tag, Bevölkerung, Glück, durchschnittliches Bewusstsein und Sprachstufe werden in Echtzeit angezeigt. Bei aktivem WARP erscheint die Zieljahrgangsanzeige in Gelb.', fr: "Année, jour, population, bonheur, conscience moyenne et stade du langage sont affichés en temps réel. Quand le WARP est actif, l'indicateur d'année cible apparaît en jaune.", ar: 'يتم عرض السنة واليوم والسكان والسعادة ومتوسط الوعي ومرحلة اللغة في الوقت الفعلي. عند تنشيط WARP تظهر مؤشر السنة المستهدفة باللون الأصفر.' } },

  // ── 3. KONTROLLER ─────────────────────────────────────────────────────────
  { kind: 'h', text: { tr: '3 — KONTROLLER', en: '3 — CONTROLS', de: '3 — STEUERUNG', fr: '3 — CONTRÔLES', ar: '٣ — عناصر التحكم' } },
  { kind: 'row', label: { tr: 'Başlat / Durdur', en: 'Start / Pause', de: 'Start / Pause', fr: 'Démarrer / Pause', ar: 'تشغيل / إيقاف مؤقت' }, value: { tr: 'Simülasyonu çalıştırır veya duraklatır. Duraklatma anında durum otomatik olarak kaydedilir.', en: 'Runs or pauses the simulation. On pause, state is automatically saved.', de: 'Startet oder pausiert die Simulation. Beim Pausieren wird der Zustand automatisch gespeichert.', fr: "Lance ou met en pause la simulation. En pause, l'état est automatiquement sauvegardé.", ar: 'يشغّل المحاكاة أو يوقفها مؤقتاً. عند الإيقاف المؤقت، يتم حفظ الحالة تلقائياً.' } },
  { kind: 'row', label: { tr: 'Hız (×1 / ×5 / ×20 / ×100)', en: 'Speed (×1 / ×5 / ×20 / ×100)', de: 'Tempo (×1 / ×5 / ×20 / ×100)', fr: 'Vitesse (×1 / ×5 / ×20 / ×100)', ar: 'السرعة (×1 / ×5 / ×20 / ×100)' }, value: { tr: 'Dört hazır hız kademesi arasında geçiş yapın veya özel bir değer yazın. ×1 gerçek zamanlı gözlem; ×100 hızlı medeniyet gelişimi için idealdir.', en: 'Switch between four preset speed levels or type a custom value. ×1 is real-time observation; ×100 is ideal for rapid civilisation development.', de: 'Wechseln Sie zwischen vier voreingestellten Geschwindigkeitsstufen oder geben Sie einen benutzerdefinierten Wert ein. ×1 ist Echtzeit-Beobachtung; ×100 ist ideal für eine schnelle Zivilisationsentwicklung.', fr: "Basculez entre quatre niveaux de vitesse prédéfinis ou saisissez une valeur personnalisée. ×1 est l'observation en temps réel ; ×100 est idéal pour un développement rapide de la civilisation.", ar: 'بدّل بين أربعة مستويات سرعة محددة مسبقاً أو اكتب قيمة مخصصة. ×1 للمراقبة الفورية؛ و×100 مثالي لتطور الحضارة السريع.' } },
  { kind: 'row', label: { tr: 'IŞINIL GİT (Warp)', en: 'WARP TO', de: 'WARP ZU', fr: 'WARP VERS', ar: 'قفز إلى' }, value: { tr: 'Hedef bir yıl girerek simülasyonu o yıla ışınlayın. Warp aktifken tüm motorlar arka planda maksimum hızda çalışır; iptal etmek için WARP AKTİF düğmesine basın.', en: 'Enter a target year to warp the simulation to that point. While warping all engines run in the background at maximum speed; press WARPING to cancel.', de: 'Geben Sie ein Zieljahr ein, um die Simulation zu diesem Zeitpunkt zu teleportieren. Während des Warps laufen alle Engines im Hintergrund mit maximaler Geschwindigkeit; drücken Sie WARP AKTIV zum Abbrechen.', fr: "Saisissez une année cible pour transporter la simulation à ce moment. Pendant le warp, tous les moteurs fonctionnent en arrière-plan à vitesse maximale ; appuyez sur WARP ACTIF pour annuler.", ar: 'أدخل سنة مستهدفة لنقل المحاكاة إلى تلك النقطة. أثناء القفز تعمل جميع المحركات في الخلفية بالسرعة القصوى؛ اضغط WARP نشط للإلغاء.' } },
  { kind: 'row', label: { tr: 'Menü', en: 'Menu', de: 'Menü', fr: 'Menu', ar: 'القائمة' }, value: { tr: 'Kılavuz, dil seçenekleri, proje hakkında bilgi ve iletişim sayfalarına erişim sağlar.', en: 'Provides access to the guide, language options, project information and contact pages.', de: 'Bietet Zugang zu Anleitung, Sprachoptionen, Projektinformationen und Kontaktseiten.', fr: 'Donne accès au guide, aux options de langue, aux informations sur le projet et aux pages de contact.', ar: 'يوفر الوصول إلى الدليل وخيارات اللغة ومعلومات المشروع وصفحات التواصل.' } },

  // ── 4. PANELLER ───────────────────────────────────────────────────────────
  { kind: 'h', text: { tr: '4 — PANELLER', en: '4 — PANELS', de: '4 — PANELS', fr: '4 — PANNEAUX', ar: '٤ — اللوحات' } },
  { kind: 'note', text: { tr: 'Tüm paneller sol kenar çubuğundan açılır. Her panel canlı tick akışıyla güncellenir; simülasyon duraklatılmış olsa bile son verileri gösterir.', en: 'All panels open from the left sidebar. Each panel updates with the live tick stream; it shows the latest data even when the simulation is paused.', de: 'Alle Panels öffnen sich über die linke Seitenleiste. Jedes Panel aktualisiert sich mit dem Live-Tick-Stream und zeigt die neuesten Daten, auch wenn die Simulation pausiert ist.', fr: "Tous les panneaux s'ouvrent depuis la barre latérale gauche. Chaque panneau se met à jour avec le flux de ticks en direct ; il affiche les dernières données même lorsque la simulation est en pause.", ar: 'تُفتح جميع اللوحات من الشريط الجانبي الأيسر. تتحدث كل لوحة مع تدفق التكات الحي؛ وتعرض أحدث البيانات حتى عند إيقاف المحاكاة مؤقتاً.' } },

  { kind: 'sub', text: { tr: 'Nüfus & Demografi', en: 'Population & Demographics', de: 'Bevölkerung & Demografie', fr: 'Population & Démographie', ar: 'السكان والديموغرافيا' } },
  { kind: 'row', label: { tr: 'Nüfus', en: 'Population', de: 'Bevölkerung', fr: 'Population', ar: 'السكان' }, value: { tr: 'Yaşayan bireylerin listesi. Her kişiye tıklandığında isim, yaş, cinsiyet, bilinç düzeyi, aile bağları, iç ses düşünceleri, kişilik özellikleri, sağlık durumu ve yaşam hikâyesi görülür.', en: "List of living individuals. Clicking a person shows name, age, sex, consciousness level, family links, inner voice thoughts, personality traits, health status and life story.", de: 'Liste der lebenden Individuen. Ein Klick auf eine Person zeigt Name, Alter, Geschlecht, Bewusstseinsstufe, Familienbindungen, innere Stimme, Persönlichkeitsmerkmale, Gesundheitszustand und Lebensgeschichte.', fr: "Liste des individus vivants. Cliquer sur une personne affiche le nom, l'âge, le sexe, le niveau de conscience, les liens familiaux, les pensées de la voix intérieure, les traits de personnalité, l'état de santé et l'histoire de vie.", ar: 'قائمة الأفراد الأحياء. النقر على شخص يُظهر الاسم والعمر والجنس ومستوى الوعي وروابط الأسرة وأفكار الصوت الداخلي وسمات الشخصية والحالة الصحية وقصة الحياة.' } },
  { kind: 'row', label: { tr: 'Nüfus Piramidi', en: 'Population Pyramid', de: 'Bevölkerungspyramide', fr: 'Pyramide des âges', ar: 'هرم السكان' }, value: { tr: 'Yaşa ve cinsiyete göre nüfus dağılımını yatay çubuk grafik olarak gösterir. Erkek sol, kadın sağ tarafta; cinsiyet oranı ve toplam sayılar özet olarak sunulur.', en: 'Shows population distribution by age and sex as a horizontal bar chart. Males on the left, females on the right; sex ratio and total counts summarised.', de: 'Zeigt die Bevölkerungsverteilung nach Alter und Geschlecht als horizontales Balkendiagramm. Männer links, Frauen rechts; Geschlechterverhältnis und Gesamtzahlen werden zusammengefasst.', fr: 'Affiche la répartition de la population par âge et sexe sous forme de graphique à barres horizontales. Hommes à gauche, femmes à droite ; ratio des sexes et totaux résumés.', ar: 'يعرض توزيع السكان حسب العمر والجنس كمخطط شريطي أفقي. الذكور على اليسار والإناث على اليمين؛ مع ملخص نسبة الجنس والأعداد الإجمالية.' } },
  { kind: 'row', label: { tr: 'Soy Ağacı', en: 'Genealogy', de: 'Stammbaum', fr: 'Généalogie', ar: 'شجرة الأنساب' }, value: { tr: 'Kurucudan başlayarak dört nesle kadar aile ağacı görselleştirilir. Erkek ve kadın hatları farklı renklerle ayrıştırılır.', en: 'Visualises the family tree up to four generations starting from each founder. Male and female lineages are distinguished by colour.', de: 'Visualisiert den Familienstammbaum bis zu vier Generationen ab jedem Gründer. Männliche und weibliche Linien werden farblich unterschieden.', fr: "Visualise l'arbre généalogique jusqu'à quatre générations à partir de chaque fondateur. Les lignées masculines et féminines sont distinguées par couleur.", ar: 'يُصوّر شجرة العائلة حتى أربعة أجيال بدءاً من كل مؤسس. يتم تمييز الخطوط الذكورية والأنثوية بالألوان.' } },

  { kind: 'sub', text: { tr: 'Bilim & Keşif', en: 'Science & Discovery', de: 'Wissenschaft & Entdeckung', fr: 'Science & Découverte', ar: 'العلم والاكتشاف' } },
  { kind: 'row', label: { tr: 'Teknoloji', en: 'Technology', de: 'Technologie', fr: 'Technologie', ar: 'التكنولوجيا' }, value: { tr: 'Beş kademeli teknoloji ağacını ve keşifleri gösterir. Her keşfin kim tarafından, kaçıncı yılda, hangi yaş ve merak düzeyiyle gerçekleştiği kayıt altına alınır.', en: 'Shows the five-tier technology tree and all discoveries. Each discovery records who made it, in which year, and at what age and curiosity level.', de: 'Zeigt den fünfstufigen Technologiebaum und alle Entdeckungen. Jede Entdeckung verzeichnet, wer sie gemacht hat, in welchem Jahr und mit welchem Alter und Neugierdeniveau.', fr: "Affiche l'arbre technologique à cinq niveaux et toutes les découvertes. Chaque découverte enregistre qui l'a faite, en quelle année et à quel âge et niveau de curiosité.", ar: 'يعرض شجرة التكنولوجيا ذات الخمسة مستويات وجميع الاكتشافات. تُسجّل كل اكتشاف من اكتشفه وفي أي عام وبأي عمر ومستوى فضول.' } },
  { kind: 'row', label: { tr: 'Astronomi', en: 'Astronomy', de: 'Astronomie', fr: 'Astronomie', ar: 'الفلك' }, value: { tr: 'Beş bilgi kademesini (ay takibi, mevsim takvimi, yıldız haritası, tutulma tahmini, gezegen modeli) ve gözlemlenen gök olaylarını izler. Her kademe belirli zeka, FOXP2 ve teknoloji eşiklerini gerektirir.', en: 'Tracks five knowledge tiers (lunar tracking, seasonal calendar, star map, eclipse prediction, planetary model) and observed celestial events. Each tier requires specific intelligence, FOXP2 and technology thresholds.', de: 'Verfolgt fünf Wissensstufen (Mondverfolgung, Saisonkalender, Sternenkarte, Finsternisvorhersage, Planetenmodell) und beobachtete Himmelsereignisse. Jede Stufe erfordert bestimmte Intelligenz-, FOXP2- und Technologieschwellen.', fr: "Suit cinq niveaux de connaissance (suivi lunaire, calendrier saisonnier, carte stellaire, prédiction d'éclipse, modèle planétaire) et les événements célestes observés. Chaque niveau nécessite des seuils spécifiques d'intelligence, de FOXP2 et de technologie.", ar: 'يتتبع خمسة مستويات للمعرفة (تتبع القمر، التقويم الموسمي، خريطة النجوم، التنبؤ بالكسوف، نموذج الكواكب) والأحداث السماوية المرصودة. يتطلب كل مستوى حدوداً محددة للذكاء وFOXP2 والتكنولوجيا.' } },
  { kind: 'row', label: { tr: 'Epigenetik', en: 'Epigenetics', de: 'Epigenetik', fr: 'Épigénétique', ar: 'علم الجينات اللاجينية' }, value: { tr: 'Sekiz genetik lokus üzerindeki metilasyon yüzdelerini ve kuşaklar arası kalıtım oranlarını gösterir. Epigenetik yaş, kronolojik yaştan farklılık gösterebilir.', en: 'Shows methylation percentages across eight genetic loci and transgenerational heritability rates. Epigenetic age can differ from chronological age.', de: 'Zeigt Methylierungsprozentsätze über acht Genloci und transgenerationale Erblichkeitsraten. Das epigenetische Alter kann vom chronologischen Alter abweichen.', fr: "Affiche les pourcentages de méthylation sur huit loci génétiques et les taux d'héritabilité transgénérationnelle. L'âge épigénétique peut différer de l'âge chronologique.", ar: 'يعرض نسب الميثيلة عبر ثمانية مواقع جينية ومعدلات الوراثة عبر الأجيال. قد يختلف العمر اللاجيني عن العمر الزمني.' } },

  { kind: 'sub', text: { tr: 'Kültür & Sanat', en: 'Culture & Art', de: 'Kultur & Kunst', fr: 'Culture & Art', ar: 'الثقافة والفن' } },
  { kind: 'row', label: { tr: 'Kültür', en: 'Culture', de: 'Kultur', fr: 'Culture', ar: 'الثقافة' }, value: { tr: 'Kültürel mem sayısını ve beş gelişim kademesini görselleştirir. Kültürel gelişimin olay akışı canlı takip edilebilir.', en: 'Visualises cultural meme count and five development stages. The cultural development event stream can be followed live.', de: 'Visualisiert die Anzahl kultureller Meme und fünf Entwicklungsstufen. Der Ereignisstrom der kulturellen Entwicklung kann live verfolgt werden.', fr: "Visualise le nombre de mèmes culturels et cinq stades de développement. Le flux d'événements du développement culturel peut être suivi en direct.", ar: 'يُصوّر عدد الميمات الثقافية وخمس مراحل تطور. يمكن متابعة تدفق أحداث التطور الثقافي مباشرةً.' } },
  { kind: 'row', label: { tr: 'Sanat', en: 'Art', de: 'Kunst', fr: 'Art', ar: 'الفن' }, value: { tr: '12 sanat formunu (görsel, müzik, anlatı) kategorilere göre gösterir. Her formun keşfi için gereken besin fazlası, sanat duygusu ve teknik ön koşullar listelenir.', en: 'Shows 12 art forms (visual, music, narrative) by category. Lists food surplus, art sense and technical prerequisites required to discover each form.', de: 'Zeigt 12 Kunstformen (visuell, Musik, Narrativ) nach Kategorie. Listet den Nahrungsüberschuss, den Kunstsinn und die technischen Voraussetzungen für die Entdeckung jeder Form auf.', fr: "Affiche 12 formes d'art (visuel, musique, narratif) par catégorie. Liste les excédents alimentaires, le sens artistique et les prérequis techniques pour découvrir chaque forme.", ar: 'يعرض 12 شكلاً فنياً (بصري، موسيقى، سردي) حسب الفئة. يسرد فائض الغذاء والحس الفني والمتطلبات التقنية اللازمة لاكتشاف كل شكل.' } },
  { kind: 'row', label: { tr: 'İnanç', en: 'Belief', de: 'Glaube', fr: 'Croyance', ar: 'المعتقد' }, value: { tr: 'İnanç sistemi arketiplerini ve ortaya çıkış koşullarını gösterir. İnanç oluşumu dindarlık geni, kaygı düzeyi ve çevresel stres eşiklerine bağlıdır. Ritüel olay günlüğü tutulur.', en: 'Shows belief system archetypes and emergence conditions. Belief formation depends on the religiosity gene, anxiety level and environmental stress thresholds. A ritual event log is maintained.', de: 'Zeigt Glaubenssystem-Archetypen und Entstehungsbedingungen. Die Glaubensbildung hängt vom Religiositätsgen, dem Angstlevel und den Umweltstressschwellen ab. Ein Ritualeventlog wird geführt.', fr: "Affiche les archétypes de systèmes de croyances et les conditions d'émergence. La formation des croyances dépend du gène de religiosité, du niveau d'anxiété et des seuils de stress environnemental. Un journal des événements rituels est tenu.", ar: 'يعرض أنماط نظام المعتقدات وشروط الظهور. يعتمد تكوّن المعتقد على جين التديّن ومستوى القلق وحدود الإجهاد البيئي. يُحتفظ بسجل أحداث الطقوس.' } },
  { kind: 'row', label: { tr: 'Dil', en: 'Language', de: 'Sprache', fr: 'Langage', ar: 'اللغة' }, value: { tr: 'Altı dil evrim kademesini, sesgrup gelişimini (ünsüzler, ünlüler, yüzey biçimleri) ve diyalekt ayrışmasını izler. Dil olayları arşivlenebilir ve filtrelenebilir.', en: 'Tracks six language evolution stages, phonology development (consonants, vowels, surface forms) and dialect divergence. Language events can be archived and filtered.', de: 'Verfolgt sechs Sprachentwicklungsstufen, Phonologieentwicklung (Konsonanten, Vokale, Oberflächenformen) und Dialektdivergenz. Sprachereignisse können archiviert und gefiltert werden.', fr: "Suit six stades d'évolution du langage, le développement de la phonologie (consonnes, voyelles, formes de surface) et la divergence dialectale. Les événements linguistiques peuvent être archivés et filtrés.", ar: 'يتتبع ست مراحل لتطور اللغة وتطور علم الأصوات (الصوامت والحركات والأشكال السطحية) وتشعب اللهجات. يمكن أرشفة أحداث اللغة وتصفيتها.' } },
  { kind: 'row', label: { tr: 'Mimari', en: 'Architecture', de: 'Architektur', fr: 'Architecture', ar: 'العمارة' }, value: { tr: 'İnşa edilen yapı sayısını ve dört kademe yapı tipini (doğal, basit, kalıcı, kentsel) gösterir. İnşaat olayları günlüğe kaydedilir.', en: 'Shows total structures built and four tiers of structure types (natural, simple, permanent, urban). Construction events are logged.', de: 'Zeigt die Gesamtzahl der gebauten Strukturen und vier Stufen von Strukturtypen (natürlich, einfach, dauerhaft, urban). Bauereignisse werden protokolliert.', fr: "Affiche le nombre total de structures construites et quatre niveaux de types de structures (naturel, simple, permanent, urbain). Les événements de construction sont consignés.", ar: 'يعرض العدد الإجمالي للمنشآت المبنية وأربعة مستويات من أنواع المنشآت (طبيعية، بسيطة، دائمة، حضرية). يتم تسجيل أحداث البناء.' } },

  { kind: 'sub', text: { tr: 'Toplum & Ekonomi', en: 'Society & Economy', de: 'Gesellschaft & Wirtschaft', fr: 'Société & Économie', ar: 'المجتمع والاقتصاد' } },
  { kind: 'row', label: { tr: 'Sosyal Yapı', en: 'Social Structure', de: 'Sozialstruktur', fr: 'Structure sociale', ar: 'البنية الاجتماعية' }, value: { tr: 'Grup sayısını, çatışmaları, liderlik değişikliklerini ve nüfus bölünmelerini izler. Rol ataması (lider, savaşçı, şifacı, yaşlı, üye) ve hiyerarşi gelişimi modellenir.', en: 'Tracks group count, conflicts, leadership changes and population splits. Role assignment (leader, warrior, healer, elder, member) and hierarchy development are modelled.', de: 'Verfolgt Gruppenanzahl, Konflikte, Führungswechsel und Bevölkerungsspaltungen. Rollenzuweisung (Anführer, Krieger, Heiler, Ältester, Mitglied) und Hierarchieentwicklung werden modelliert.', fr: "Suit le nombre de groupes, les conflits, les changements de leadership et les scissions de population. L'attribution de rôles (chef, guerrier, guérisseur, aîné, membre) et le développement de la hiérarchie sont modélisés.", ar: 'يتتبع عدد المجموعات والصراعات وتغييرات القيادة وانقسامات السكان. يتم نمذجة تعيين الأدوار (قائد، محارب، شافٍ، شيخ، عضو) وتطور التسلسل الهرمي.' } },
  { kind: 'row', label: { tr: 'Ekonomi', en: 'Economy', de: 'Wirtschaft', fr: 'Économie', ar: 'الاقتصاد' }, value: { tr: 'Ortalama refah, Gini katsayısı (eşitsizlik) ve kaynak dağılım grafiğini gösterir. Takas ekonomisi; besin fazlası, altruizm geni ve işbirliği düzeyine göre çalışır.', en: 'Shows average wealth, Gini coefficient (inequality) and resource distribution chart. The barter economy operates based on food surplus, the altruism gene and cooperation level.', de: 'Zeigt durchschnittlichen Wohlstand, Gini-Koeffizient (Ungleichheit) und Ressourcenverteilungsdiagramm. Die Tauschwirtschaft funktioniert basierend auf Nahrungsüberschuss, dem Altruismusgen und dem Kooperationsniveau.', fr: "Affiche la richesse moyenne, le coefficient de Gini (inégalité) et le graphique de distribution des ressources. L'économie de troc fonctionne en fonction de l'excédent alimentaire, du gène d'altruisme et du niveau de coopération.", ar: 'يعرض متوسط الثروة ومعامل جيني (عدم المساواة) ومخطط توزيع الموارد. تعمل اقتصاد المقايضة بناءً على فائض الغذاء وجين الإيثار ومستوى التعاون.' } },
  { kind: 'row', label: { tr: 'Hukuk & Normlar', en: 'Law & Norms', de: 'Recht & Normen', fr: 'Droit & Normes', ar: 'القانون والأعراف' }, value: { tr: 'Normların dört evrim kademesini (kendiliğinden, sosyal, proto-hukuk, resmi) ve aktif norm sayısını izler. İhlaller kayıt altına alınır.', en: 'Tracks four norm evolution stages (spontaneous, social, proto-law, formal) and active norm count. Violations are recorded.', de: 'Verfolgt vier Normentwicklungsstufen (spontan, sozial, Proto-Recht, formal) und die Anzahl aktiver Normen. Verstöße werden aufgezeichnet.', fr: "Suit quatre stades d'évolution des normes (spontané, social, proto-droit, formel) et le nombre de normes actives. Les violations sont enregistrées.", ar: 'يتتبع أربع مراحل لتطور الأعراف (تلقائي، اجتماعي، قانون بدائي، رسمي) وعدد الأعراف النشطة. يتم تسجيل الانتهاكات.' } },
  { kind: 'row', label: { tr: 'Psikoloji', en: 'Psychology', de: 'Psychologie', fr: 'Psychologie', ar: 'علم النفس' }, value: { tr: 'Nüfus mutluluk yüzdesini, bilişsel metrikleri (zeka, bilinç, esenlik, stres), Theory of Mind dağılımını ve zihinsel durum dökümünü gösterir.', en: 'Shows population happiness percentage, cognitive metrics (intelligence, consciousness, wellbeing, stress), Theory of Mind distribution and mental state breakdown.', de: 'Zeigt den Bevölkerungsglücksprozentsatz, kognitive Metriken (Intelligenz, Bewusstsein, Wohlbefinden, Stress), Theory of Mind-Verteilung und Geisteszustandsaufschlüsselung.', fr: "Affiche le pourcentage de bonheur de la population, les métriques cognitives (intelligence, conscience, bien-être, stress), la distribution de la Théorie de l'esprit et la ventilation des états mentaux.", ar: 'يعرض نسبة سعادة السكان والمقاييس المعرفية (الذكاء والوعي والرفاهية والإجهاد) وتوزيع نظرية العقل وتفاصيل الحالة النفسية.' } },

  { kind: 'sub', text: { tr: 'Sağlık & Çevre', en: 'Health & Environment', de: 'Gesundheit & Umwelt', fr: 'Santé & Environnement', ar: 'الصحة والبيئة' } },
  { kind: 'row', label: { tr: 'Biyoloji', en: 'Biology', de: 'Biologie', fr: 'Biologie', ar: 'الأحياء' }, value: { tr: 'Nüfus yaşam istatistiklerini (ortalama yaş, cinsiyet oranı, zeka dağılımı, bilinç seviyeleri), genom aktivitesini ve yaşam evreleri dağılımını (çocuk, yetişkin, yaşlı) gösterir.', en: 'Shows population vital statistics (average age, sex ratio, intelligence distribution, consciousness levels), genome activity and life stage distribution (child, adult, elder).', de: 'Zeigt Bevölkerungsvitalstatistiken (Durchschnittsalter, Geschlechterverhältnis, Intelligenzverteilung, Bewusstseinsniveaus), Genomaktivität und Lebensstadienverteilung (Kind, Erwachsener, Älterer).', fr: "Affiche les statistiques vitales de la population (âge moyen, ratio des sexes, distribution de l'intelligence, niveaux de conscience), l'activité génomique et la distribution des stades de vie (enfant, adulte, aîné).", ar: 'يعرض إحصاءات حيوية للسكان (متوسط العمر ونسبة الجنس وتوزيع الذكاء ومستويات الوعي) ونشاط الجينوم وتوزيع مراحل الحياة (طفل، بالغ، شيخ).' } },
  { kind: 'row', label: { tr: 'Mikrobiyom & Hastalık', en: 'Microbiome & Disease', de: 'Mikrobiom & Krankheit', fr: 'Microbiome & Maladie', ar: 'الميكروبيوم والمرض' }, value: { tr: 'Hastalık oranını, aktif patojen tiplerini (bağırsak paraziti, kolera benzeri, solunum, veba benzeri, sıtma benzeri ve daha fazlası) ve salgın geçmişini izler. Bağışıklık geni hastalık direncini belirler.', en: 'Tracks sick rate, active pathogen types (intestinal parasite, cholera-like, respiratory, plague-like, malaria-like and more) and epidemic history. The immunity gene determines disease resistance.', de: 'Verfolgt Krankheitsrate, aktive Pathogentypen (Darmparasit, choleraähnlich, Atemwegs-, pestartig, malariaähnlich und mehr) und Epidemiegeschichte. Das Immunitätsgen bestimmt die Krankheitsresistenz.', fr: "Suit le taux de maladie, les types de pathogènes actifs (parasite intestinal, type choléra, respiratoire, type peste, type paludisme et plus) et l'historique des épidémies. Le gène d'immunité détermine la résistance aux maladies.", ar: 'يتتبع معدل المرض وأنواع مسببات الأمراض النشطة (طفيل معوي، كوليرا، تنفسي، طاعون، ملاريا وغيرها) وتاريخ الأوبئة. يحدد جين المناعة مقاومة الأمراض.' } },
  { kind: 'row', label: { tr: 'Çevre', en: 'Environment', de: 'Umwelt', fr: 'Environnement', ar: 'البيئة' }, value: { tr: 'Aktif biyomu, mevsimi, hava koşullarını (yağış, nem, rüzgar hızı, UV indeksi) ve afet geçmişini gösterir. Besin ve su bolluğu %0-100 arasında renk kodlu gösterilir.', en: 'Shows active biome, season, weather conditions (precipitation, humidity, wind speed, UV index) and disaster history. Food and water abundance shown colour-coded from 0-100%.', de: 'Zeigt aktives Biom, Jahreszeit, Wetterbedingungen (Niederschlag, Luftfeuchtigkeit, Windgeschwindigkeit, UV-Index) und Katastrophengeschichte. Nahrungsreichtum und Wasserreichtum werden farbcodiert von 0-100% angezeigt.', fr: "Affiche le biome actif, la saison, les conditions météorologiques (précipitations, humidité, vitesse du vent, indice UV) et l'historique des catastrophes. Abondance de nourriture et d'eau affichées avec code couleur de 0 à 100%.", ar: 'يعرض المنطقة الحيوية النشطة والموسم وأحوال الطقس (هطول الأمطار والرطوبة وسرعة الرياح ومؤشر الأشعة فوق البنفسجية) وتاريخ الكوارث. تُعرض وفرة الغذاء والماء بترميز لوني من 0 إلى 100%.' } },

  { kind: 'sub', text: { tr: 'İzleme & Analiz', en: 'Monitoring & Analysis', de: 'Überwachung & Analyse', fr: 'Suivi & Analyse', ar: 'المراقبة والتحليل' } },
  { kind: 'row', label: { tr: 'İstatistikler', en: 'Statistics', de: 'Statistiken', fr: 'Statistiques', ar: 'الإحصاءات' }, value: { tr: 'Sürüklenebilir yüzen panel. Nüfus, besin, su, mutluluk, bilinç ve dil metrikleri seçilerek çizgi grafik olarak geçmiş verileri görselleştirilir.', en: 'A draggable floating panel. Select population, food, water, happiness, consciousness and language metrics to visualise historical data as a line chart.', de: 'Ein ziehbares schwebendes Panel. Wählen Sie Bevölkerung, Nahrung, Wasser, Glück, Bewusstsein und Sprachmetriken aus, um historische Daten als Liniendiagramm zu visualisieren.', fr: "Un panneau flottant déplaçable. Sélectionnez les métriques de population, nourriture, eau, bonheur, conscience et langage pour visualiser les données historiques sous forme de graphique linéaire.", ar: 'لوحة عائمة قابلة للسحب. اختر مقاييس السكان والغذاء والماء والسعادة والوعي واللغة لتصوير البيانات التاريخية كمخطط خطي.' } },
  { kind: 'row', label: { tr: 'Performans', en: 'Performance', de: 'Leistung', fr: 'Performance', ar: 'الأداء' }, value: { tr: 'Warp modu durumunu, tick zamanlama metriklerini (ort/max/min ms), saniyedeki tick sayısını, mevcut gün ve nüfusu ve ulaşılan kilometre taşlarını gösterir. Başlangıç ve mevcut konum koordinatları da görüntülenir.', en: 'Shows warp mode status, tick timing metrics (avg/max/min ms), ticks per second, current day and population, and reached milestones. Start and current location coordinates are also displayed.', de: 'Zeigt den Warp-Modus-Status, Tick-Timing-Metriken (Durchschnitt/Max/Min ms), Ticks pro Sekunde, aktuellen Tag und Bevölkerung sowie erreichte Meilensteine. Start- und aktuelle Standortkoordinaten werden ebenfalls angezeigt.', fr: "Affiche l'état du mode warp, les métriques de timing des ticks (moy/max/min ms), les ticks par seconde, le jour actuel et la population, et les jalons atteints. Les coordonnées de départ et actuelles sont également affichées.", ar: 'يعرض حالة وضع الوارب ومقاييس توقيت التكات (متوسط/أقصى/أدنى بالمللي ثانية) والتكات في الثانية واليوم الحالي والسكان والمعالم المحققة. تُعرض أيضاً إحداثيات الموقع البادئ والحالي.' } },
  { kind: 'row', label: { tr: 'Anlar', en: 'Moments', de: 'Momente', fr: 'Moments', ar: 'اللحظات' }, value: { tr: 'Simülasyon tarihindeki önemli olayları anlık fotoğraflarla kaydeder. Her an; ikon, renk, başlık, açıklama ve zaman damgasıyla gösterilir.', en: 'Records important events in simulation history as snapshots. Each moment is shown with an icon, colour, title, description and timestamp.', de: 'Zeichnet wichtige Ereignisse in der Simulationsgeschichte als Schnappschüsse auf. Jeder Moment wird mit einem Symbol, einer Farbe, einem Titel, einer Beschreibung und einem Zeitstempel angezeigt.', fr: "Enregistre les événements importants de l'histoire de la simulation sous forme de captures. Chaque moment est affiché avec une icône, une couleur, un titre, une description et un horodatage.", ar: 'يُسجّل الأحداث المهمة في تاريخ المحاكاة كلقطات فورية. تُعرض كل لحظة بأيقونة ولون وعنوان ووصف وطابع زمني.' } },
  { kind: 'row', label: { tr: 'Rapor', en: 'Report', de: 'Bericht', fr: 'Rapport', ar: 'التقرير' }, value: { tr: 'JSON veya PDF formatında kapsamlı rapor ihraç eder. İstatistikler, zaman çizelgeleri, göç güzergâhları, ölüm istatistikleri ve soy ağacı bilgilerini içerir.', en: 'Exports a comprehensive report in JSON or PDF format. Includes statistics, timelines, migration paths, death statistics and genealogy data.', de: 'Exportiert einen umfassenden Bericht im JSON- oder PDF-Format. Enthält Statistiken, Zeitpläne, Migrationspfade, Sterbestatistiken und Stammbaumdaten.', fr: "Exporte un rapport complet au format JSON ou PDF. Comprend des statistiques, des chronologies, des chemins migratoires, des statistiques de mortalité et des données généalogiques.", ar: 'يُصدّر تقريراً شاملاً بصيغة JSON أو PDF. يشمل الإحصاءات والجداول الزمنية ومسارات الهجرة وإحصاءات الوفاة وبيانات الأنساب.' } },

  // ── 5. OLAY AKIŞI ─────────────────────────────────────────────────────────
  { kind: 'h', text: { tr: '5 — OLAY AKIŞI', en: '5 — EVENT FEED', de: '5 — EREIGNISFEED', fr: "5 — FLUX D'ÉVÉNEMENTS", ar: '٥ — تدفق الأحداث' } },
  { kind: 'bullet', text: { tr: 'Doğum, ölüm, keşif, çatışma, salgın, inanç, kültür, sanat, astronomi, göç ve hukuk normları dahil 10+ kategoride olaylar canlı yayınlanır.', en: 'Events in 10+ categories including birth, death, discovery, conflict, epidemic, belief, culture, art, astronomy, migration and legal norms are broadcast live.', de: 'Ereignisse in 10+ Kategorien einschließlich Geburt, Tod, Entdeckung, Konflikt, Epidemie, Glaube, Kultur, Kunst, Astronomie, Migration und Rechtsnormen werden live übertragen.', fr: "Les événements dans plus de 10 catégories dont naissance, mort, découverte, conflit, épidémie, croyance, culture, art, astronomie, migration et normes juridiques sont diffusés en direct.", ar: 'تُبث أحداث في أكثر من 10 فئات تشمل ولادة ووفاة واكتشاف وصراع ووباء ومعتقد وثقافة وفن وفلك وهجرة وأعراف قانونية مباشرةً.' } },
  { kind: 'bullet', text: { tr: 'Olaylar renk kodlu gösterilir ve kategoriye göre filtrelenebilir. Arama özelliğiyle arşivden geçmiş olaylar sorgulanabilir.', en: 'Events are colour-coded and can be filtered by category. The archive search lets you query past events.', de: 'Ereignisse sind farbkodiert und können nach Kategorie gefiltert werden. Die Archivsuche ermöglicht die Abfrage vergangener Ereignisse.', fr: "Les événements sont codés par couleur et peuvent être filtrés par catégorie. La recherche dans les archives permet d'interroger les événements passés.", ar: 'الأحداث مرمّزة بالألوان ويمكن تصفيتها حسب الفئة. يتيح البحث في الأرشيف الاستعلام عن الأحداث الماضية.' } },

  // ── 6. HİPOTEZ & ANALİZ ──────────────────────────────────────────────────
  { kind: 'h', text: { tr: '6 — HİPOTEZ & ANALİZ', en: '6 — HYPOTHESIS & ANALYSIS', de: '6 — HYPOTHESE & ANALYSE', fr: '6 — HYPOTHÈSE & ANALYSE', ar: '٦ — الفرضية والتحليل' } },
  { kind: 'row', label: { tr: 'Hipotez Testi', en: 'Hypothesis Test', de: 'Hypothesentest', fr: "Test d'hypothèse", ar: 'اختبار الفرضية' }, value: { tr: 'Önceden tanımlı veya özel hipotezler girilir; sistem gerçek simülasyon verisiyle sınar ve güven yüzdesi ile %95 güven aralığı sunar. Adem & Havva temel metrikleri (bilinç, ToM, kelime sayısı, teknoloji, sanat) doğrudan görülür.', en: 'Enter predefined or custom hypotheses; the system tests them against live simulation data and returns a confidence percentage with 95% confidence intervals. Core Adam & Eve metrics (consciousness, ToM, word count, technology, art) are shown directly.', de: 'Geben Sie vordefinierte oder benutzerdefinierte Hypothesen ein; das System testet sie anhand von Live-Simulationsdaten und gibt einen Vertrauensprozentsatz mit 95%-Konfidenzintervallen zurück. Kern-Adam-&-Eva-Metriken (Bewusstsein, ToM, Wortanzahl, Technologie, Kunst) werden direkt angezeigt.', fr: "Saisissez des hypothèses prédéfinies ou personnalisées ; le système les teste sur des données de simulation en direct et renvoie un pourcentage de confiance avec des intervalles de confiance à 95%. Les métriques fondamentales Adam & Ève (conscience, ToM, nombre de mots, technologie, art) sont affichées directement.", ar: 'أدخل فرضيات محددة مسبقاً أو مخصصة؛ يختبرها النظام مقابل بيانات المحاكاة الحية ويُعيد نسبة ثقة مع فترات ثقة 95%. تُعرض المقاييس الأساسية لآدم وحواء (الوعي وToM وعدد الكلمات والتكنولوجيا والفن) مباشرةً.' } },
  { kind: 'row', label: { tr: 'BOLD Asistanı', en: 'BOLD Assistant', de: 'BOLD-Assistent', fr: 'Assistant BOLD', ar: 'مساعد BOLD' }, value: { tr: 'Yapay zeka destekli analiz arayüzü. Hazır sorulardan seçebilir veya serbest metin girebilirsiniz. Asistan canlı simülasyon istatistiklerini ve olay verilerini okuyarak yanıt üretir.', en: 'AI-powered analysis interface. Choose from preset questions or enter free text. The assistant reads live simulation statistics and event data to generate answers.', de: 'KI-gestützte Analyseoberfläche. Wählen Sie aus vordefinierten Fragen oder geben Sie freien Text ein. Der Assistent liest Live-Simulationsstatistiken und Ereignisdaten zur Antwortgenerierung.', fr: "Interface d'analyse propulsée par IA. Choisissez parmi des questions prédéfinies ou entrez du texte libre. L'assistant lit les statistiques de simulation en direct et les données d'événements pour générer des réponses.", ar: 'واجهة تحليل مدعومة بالذكاء الاصطناعي. اختر من الأسئلة المعدّة مسبقاً أو أدخل نصاً حراً. يقرأ المساعد إحصاءات المحاكاة الحية وبيانات الأحداث لتوليد الإجابات.' } },

  // ── 7. ARIA ASİSTANI ──────────────────────────────────────────────────────
  { kind: 'h', text: { tr: '7 — ARIA ASİSTANI', en: '7 — ARIA ASSISTANT', de: '7 — ARIA-ASSISTENT', fr: '7 — ASSISTANT ARIA', ar: '٧ — مساعد ARIA' } },
  { kind: 'bullet', text: { tr: 'Aria, simülasyon sayfasındaki sesli/yazılı yapay zeka asistanıdır. Nüfus sayısı, mevcut yıl, keşiflerin listesi ve panel açma komutlarına anlık yanıt verir.', en: 'Aria is the voice/text AI assistant on the simulation page. It responds instantly to population count, current year, discovery list and panel-open commands.', de: 'Aria ist der Sprach-/Text-KI-Assistent auf der Simulationsseite. Es antwortet sofort auf Bevölkerungszahl, aktuelles Jahr, Entdeckungsliste und Panel-Öffnen-Befehle.', fr: "Aria est l'assistant IA vocal/textuel sur la page de simulation. Il répond instantanément aux commandes de nombre de population, année en cours, liste des découvertes et ouverture de panneaux.", ar: 'Aria هو المساعد الذكي الصوتي/النصي في صفحة المحاكاة. يستجيب فورياً لأوامر عدد السكان والسنة الحالية وقائمة الاكتشافات وفتح اللوحات.' } },
  { kind: 'bullet', text: { tr: 'Aria, simülasyon sihirbazı sırasında da rehberlik eder: adım adım özellik ayarlarında yardımcı olur ve mevcut özelliğin değerini sesle değiştirebilirsiniz.', en: 'Aria also guides you during the simulation wizard: it helps step by step with trait settings and you can change the current trait value by voice.', de: 'Aria begleitet Sie auch während des Simulationsassistenten: Es hilft Schritt für Schritt bei den Merkmalseinstellungen und Sie können den aktuellen Merkmalswert per Stimme ändern.', fr: "Aria vous guide également pendant l'assistant de simulation : il aide étape par étape avec les paramètres de traits et vous pouvez modifier la valeur du trait actuel par la voix.", ar: 'ترشدك Aria أيضاً أثناء معالج المحاكاة: تساعد خطوة بخطوة في إعدادات السمات ويمكنك تغيير قيمة السمة الحالية بالصوت.' } },

  // ── 8. TANRI MODU ─────────────────────────────────────────────────────────
  { kind: 'h', text: { tr: '8 — TANRI MODU', en: '8 — GOD MODE', de: '8 — GOTT-MODUS', fr: '8 — MODE DIEU', ar: '٨ — وضع الإله' } },
  { kind: 'note', text: { tr: 'Tanrı modu müdahaleleri doğal hipotez koşularından bağımsız olarak değerlendirilmelidir. Bu modun kullanıldığı simülasyonlar bilimsel karşılaştırma amacıyla ayrı tutulmalıdır.', en: 'God mode interventions must be evaluated separately from natural hypothesis runs. Simulations using this mode should be kept separate for scientific comparison purposes.', de: 'Gottesmodus-Eingriffe müssen getrennt von natürlichen Hypothesenläufen bewertet werden. Simulationen, die diesen Modus verwenden, sollten für wissenschaftliche Vergleichszwecke separat gehalten werden.', fr: "Les interventions du mode Dieu doivent être évaluées séparément des exécutions naturelles. Les simulations utilisant ce mode doivent être gardées séparées à des fins de comparaison scientifique.", ar: 'يجب تقييم تدخلات وضع الإله بشكل منفصل عن تشغيلات الفرضية الطبيعية. يجب الاحتفاظ بالمحاكاة التي تستخدم هذا الوضع منفصلة لأغراض المقارنة العلمية.' } },
  { kind: 'row', label: { tr: 'Doğal Afetler', en: 'Natural Disasters', de: 'Naturkatastrophen', fr: 'Catastrophes naturelles', ar: 'الكوارث الطبيعية' }, value: { tr: 'Deprem, sel, kuraklık, salgın, yanardağ ve meteor tetiklenebilir. Her afetin şiddeti ve etkisi ayrı ayrı ayarlanabilir.', en: 'Earthquake, flood, drought, epidemic, volcano and meteor can be triggered. Magnitude and impact can be configured for each disaster.', de: 'Erdbeben, Überschwemmung, Dürre, Seuche, Vulkan und Meteor können ausgelöst werden. Stärke und Auswirkung können für jede Katastrophe konfiguriert werden.', fr: "Tremblement de terre, inondation, sécheresse, épidémie, volcan et météore peuvent être déclenchés. L'ampleur et l'impact peuvent être configurés pour chaque catastrophe.", ar: 'يمكن تفعيل زلزال وفيضان وجفاف ووباء وبركان ونيزك. يمكن ضبط الحجم والتأثير لكل كارثة.' } },
  { kind: 'row', label: { tr: 'Bireysel Müdahaleler', en: 'Individual Interventions', de: 'Individuelle Eingriffe', fr: 'Interventions individuelles', ar: 'التدخلات الفردية' }, value: { tr: 'Seçilen bir bireye +50 yıl ömür verilebilir veya anında ölüm uygulanabilir. "Bireyle Konuş" özelliği, bireyin dil kademesine göre uyarlanmış bir yanıt üretir.', en: 'A selected individual can be granted +50 years of lifespan or instant death. The "Speak to individual" feature generates a language-stage-adapted response from the individual.', de: 'Einem ausgewählten Individuum können +50 Jahre Lebenserwartung oder sofortiger Tod gewährt werden. Die Funktion "Mit Individuum sprechen" erzeugt eine sprachstufengerechte Antwort des Individuums.', fr: "Un individu sélectionné peut recevoir +50 ans d'espérance de vie ou une mort instantanée. La fonction \"Parler à l'individu\" génère une réponse adaptée au stade linguistique de l'individu.", ar: 'يمكن منح فرد محدد +50 سنة من العمر أو الموت الفوري. تولّد ميزة "التحدث مع الفرد" استجابة متكيفة مع مرحلة اللغة من الفرد.' } },
  { kind: 'row', label: { tr: 'Karantina Modu', en: 'Quarantine Mode', de: 'Quarantänemodus', fr: 'Mode quarantaine', ar: 'وضع الحجر الصحي' }, value: { tr: 'Aktif edildiğinde tüm doğal afetler engellenir. Kontrollü gözlem deneylerinde çevre değişkenini sabitlemek için kullanılabilir.', en: 'When active, all natural disasters are suppressed. Useful for controlled observation experiments to fix the environmental variable.', de: 'Wenn aktiv, werden alle Naturkatastrophen unterdrückt. Nützlich für kontrollierte Beobachtungsexperimente zur Fixierung der Umweltvariable.', fr: "Quand actif, toutes les catastrophes naturelles sont supprimées. Utile pour les expériences d'observation contrôlées afin de fixer la variable environnementale.", ar: 'عند التنشيط تُمنع جميع الكوارث الطبيعية. مفيد في تجارب المراقبة الخاضعة للرقابة لتثبيت المتغير البيئي.' } },

  // ── 9. ZAMAN MAKİNESİ ─────────────────────────────────────────────────────
  { kind: 'h', text: { tr: '9 — ZAMAN MAKİNESİ', en: '9 — TIME MACHINE', de: '9 — ZEITMASCHINE', fr: '9 — MACHINE À REMONTER LE TEMPS', ar: '٩ — آلة الزمن' } },
  { kind: 'bullet', text: { tr: 'Manuel kontrol noktaları kaydedilebilir. Simülasyon ayrıca her 365 günde bir otomatik olarak kayıt alır.', en: 'Manual checkpoints can be saved. The simulation also auto-saves every 365 days.', de: 'Manuelle Prüfpunkte können gespeichert werden. Die Simulation erstellt außerdem alle 365 Tage automatisch eine Sicherung.', fr: "Des points de contrôle manuels peuvent être sauvegardés. La simulation effectue également une sauvegarde automatique tous les 365 jours.", ar: 'يمكن حفظ نقاط تفتيش يدوية. تقوم المحاكاة أيضاً بالحفظ التلقائي كل 365 يوم.' } },
  { kind: 'bullet', text: { tr: 'Her kontrol noktasında yıl, gün ve nüfus bilgisi görünür. İstenen bir kontrol noktasına geri dönmek için o noktaya tıklayın; simülasyon o andaki duruma yüklenir.', en: 'Each checkpoint shows year, day and population. Click a checkpoint to restore the simulation to that exact state.', de: 'Jeder Prüfpunkt zeigt Jahr, Tag und Bevölkerung. Klicken Sie auf einen Prüfpunkt, um die Simulation in diesen genauen Zustand zurückzusetzen.', fr: "Chaque point de contrôle affiche l'année, le jour et la population. Cliquez sur un point de contrôle pour restaurer la simulation à cet état exact.", ar: 'تُظهر كل نقطة تفتيش السنة واليوم والسكان. انقر على نقطة تفتيش لاستعادة المحاكاة إلى تلك الحالة بالضبط.' } },

  // ── 10. İPUÇLARI ──────────────────────────────────────────────────────────
  { kind: 'h', text: { tr: '10 — İPUÇLARI', en: '10 — TIPS', de: '10 — TIPPS', fr: '10 — CONSEILS', ar: '١٠ — نصائح' } },
  { kind: 'bullet', text: { tr: 'İlk 180 gün kritik hayatta kalma dönemidir. Besin ve su bolluğunun yüksek olduğu bir biyom seçin; tropikal veya ılıman bölgeler başlangıç için daha güvenlidir.', en: 'The first 180 days are the critical survival period. Choose a biome with high food and water abundance; tropical or temperate regions are safer for starting out.', de: 'Die ersten 180 Tage sind die kritische Überlebensperiode. Wählen Sie ein Biom mit hoher Nahrung und Wasserüberfluss; tropische oder gemäßigte Regionen sind sicherer für den Einstieg.', fr: "Les 180 premiers jours sont la période de survie critique. Choisissez un biome avec une grande abondance de nourriture et d'eau ; les régions tropicales ou tempérées sont plus sûres pour commencer.", ar: 'أول 180 يوماً هي فترة البقاء الحرجة. اختر منطقة حيوية بوفرة غذاء وماء عالية؛ المناطق الاستوائية أو المعتدلة أكثر أماناً للبداية.' } },
  { kind: 'bullet', text: { tr: 'Bilinç, dil ve teknoloji yüzyıllar içinde gelişir. ×20 veya ×100 hızda çalıştırarak ilk medeniyet sıçramalarını hızlı izleyebilirsiniz.', en: 'Consciousness, language and technology develop over centuries. Run at ×20 or ×100 to quickly watch the first civilisation leaps.', de: 'Bewusstsein, Sprache und Technologie entwickeln sich über Jahrhunderte. Laufen Sie mit ×20 oder ×100, um die ersten Zivilisationssprünge schnell zu beobachten.', fr: "La conscience, le langage et la technologie se développent sur des siècles. Exécutez à ×20 ou ×100 pour observer rapidement les premiers sauts civilisationnels.", ar: 'يتطور الوعي واللغة والتكنولوجيا على مدى قرون. اعمل بسرعة ×20 أو ×100 لمشاهدة قفزات الحضارة الأولى بسرعة.' } },
  { kind: 'bullet', text: { tr: 'Zeka ve Merak özelliklerini yüksek tutmak teknoloji ve astronomi keşiflerini önemli ölçüde hızlandırır. Bağışıklık düşük tutulursa nüfus salgınlara karşı savunmasız kalır.', en: 'Keeping Intelligence and Curiosity high significantly accelerates technology and astronomy discoveries. A low Immunity trait leaves the population vulnerable to epidemics.', de: 'Intelligenz und Neugier hoch zu halten beschleunigt Technologie- und Astronomieentdeckungen erheblich. Ein niedriges Immunitätsmerkmal lässt die Bevölkerung anfällig für Epidemien.', fr: "Maintenir l'Intelligence et la Curiosité élevées accélère considérablement les découvertes technologiques et astronomiques. Un trait d'Immunité faible laisse la population vulnérable aux épidémies.", ar: 'الحفاظ على الذكاء والفضول مرتفعَين يُسرّع بشكل ملحوظ اكتشافات التكنولوجيا والفلك. تُبقي سمة المناعة المنخفضة السكان عُرضةً للأوبئة.' } },
  { kind: 'bullet', text: { tr: 'Sanat formları yalnızca besin fazlası en az %20 olduğunda ortaya çıkabilir. Uzun süreli kıtlık kültürel gelişimi dondurur.', en: 'Art forms can only emerge when food surplus is at least 20%. Prolonged scarcity freezes cultural development.', de: 'Kunstformen können nur entstehen, wenn der Nahrungsüberschuss mindestens 20% beträgt. Anhaltende Knappheit friert die kulturelle Entwicklung ein.', fr: "Les formes d'art ne peuvent émerger que lorsque l'excédent alimentaire est d'au moins 20%. Une pénurie prolongée gèle le développement culturel.", ar: 'لا يمكن ظهور أشكال الفن إلا عندما يكون فائض الغذاء 20% على الأقل. يُجمّد الشح المطوّل التطور الثقافي.' } },
  { kind: 'bullet', text: { tr: 'Zaman Makinesini düzenli kullanın: geri dönülemez afet veya nüfus çöküşü öncesinde kontrol noktası kaydetmek farklı senaryoları karşılaştırmanızı sağlar.', en: 'Use the Time Machine regularly: saving a checkpoint before an irreversible disaster or population collapse lets you compare different scenarios.', de: 'Nutzen Sie die Zeitmaschine regelmäßig: Das Speichern eines Prüfpunkts vor einer unumkehrbaren Katastrophe oder einem Bevölkerungszusammenbruch ermöglicht es Ihnen, verschiedene Szenarien zu vergleichen.', fr: "Utilisez régulièrement la Machine à remonter le temps : sauvegarder un point de contrôle avant une catastrophe irréversible ou un effondrement de population vous permet de comparer différents scénarios.", ar: 'استخدم آلة الزمن بانتظام: حفظ نقطة تفتيش قبل كارثة لا رجعة فيها أو انهيار سكاني يتيح لك مقارنة سيناريوهات مختلفة.' } },
];

export function menuText(lang: LangCode, key: keyof typeof MENU_TEXT): string {
  return MENU_TEXT[key][lang] ?? MENU_TEXT[key].en ?? MENU_TEXT[key].tr;
}

export function pageText(lang: LangCode, key: keyof typeof PAGE_TEXT): string {
  return PAGE_TEXT[key][lang] ?? PAGE_TEXT[key].en ?? PAGE_TEXT[key].tr;
}

export function guideText(lang: LangCode, value: Translation): string {
  return value[lang] ?? value.en ?? value.tr;
}
